### ISSUE TITLE
Assess if titiler-xarray (or -pgstac) provides better visualization of MiCASA, using NetCDFs instead of COGs

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-odd#12]
```[tasklist]
### Tasks
- [x] Enable titiler-xarray can access the original NetCDFs
- [x] Use veda-ui to visualize data with titiler-xarray
- [x] Test titiler-xarray with the original NetCDFs
```

NetCDFs are here: https://portal.nccs.nasa.gov/datashare/gmao/geos_carb/MiCASA/v1/netcdf/ so we will need to put them in a bucket titiler-xarray has access to.
